version: '3'
services:

  #MySQL Service
  db:
    image: mariadb:${MARIADB_VERSION}
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes: 
      - "/var/lib/mysql/data:${DB_DATA_DIR}"
      - "/var/lib/mysql/logs:${DB_LOG_DIR}"
      - /var/docker/mariadb/conf:/etc/mysql
    networks:
      - app-network

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:${PHP_VERSION}
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./cars-website/:/var/www
      - ./docker/php/logs:/var/log/php-fpm/
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:${NGINX_VERSION}
    container_name: webserver
    restart: unless-stopped
    tty: true
#    environment:
#    - VIRTUAL_PORT=80
#    - VIRTUAL_HOST=project.local
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./cars-website/:/var/www
      - ./docker/nginx/logs:/var/log/nginx/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
    links:
      - db

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
